# Generated by Django 5.1 on 2024-08-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_alter_country_alpha2code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='additional_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha2Code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha3Code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='subregion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
