# Generated by Django 5.1 on 2024-08-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0010_alter_country_alpha2code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='alpha2Code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
