# Generated by Django 5.1 on 2024-08-23 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha2Code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha3Code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='subregion',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Subregion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.region')),
            ],
        ),
    ]
