# Generated by Django 5.1 on 2024-08-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_alter_country_capital_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='alpha2Code',
            field=models.CharField(max_length=3),
        ),
    ]
